# Diksha Fundraising App - Streamlit Secrets Configuration

[cookie]
name = "diksha_auth"
key = "45uih7kSeapyU9ZVA3wsWS9TA35-6CQ-RnvONl44t2o"
expiry_days = 7

[oauth2.google]
client_id = "564205626262-1d2h48it0b6q0dsdvb1gs0l7tbpn7rfn.apps.googleusercontent.com"
client_secret = "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"
redirect_uri = "https://web-production-94660.up.railway.app"
authorized_domains = ["dikshafoundation.org"]

[auth]
# Optional: Restrict to specific emails (leave empty to allow all @dikshafoundation.org)
allowed_emails = []
# Optional: Block specific emails
denied_emails = []