[build]
command = "npm run build"
watchPatterns = ["**/*.tsx", "**/*.ts", "**/*.js", "**/*.json"]

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"




